using System;
using System.ComponentModel.DataAnnotations;
using NCS.DSS.Sessions.Annotations;
using NCS.DSS.Sessions.ReferenceData;

namespace NCS.DSS.Sessions.Models
{
    public class SessionPatch : ISession
    {
        private const string PostcodeRegEx = @"([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9]?[A-Za-z]))))\s?[0-9][A-Za-z]{2})";

        [Display(Description = "Date and time of the session with the customer")]
        [Example(Description = "2018-06-21T14:45:00")]
        public DateTime? DateandTimeOfSession { get; set; }

        [Display(Description = "PostCode of the session or appointment venue where applicable")]
        [RegularExpression(PostcodeRegEx, ErrorMessage = "Postcode must be in valid UK format as specified in the UK Government Data Standard.")]
        [StringLength(10)]
        public string VenuePostCode { get; set; }

        [Display(Description = "Indicator to say whether the session was attended or not")]
        [Example(Description = "true/false")]
        public bool? SessionAttended { get; set; }

        [Display(Description = "Reason For Non Attendance reference data   :   " +
                                "1 - Forgot,  " +
                                "2 - No longer needed,  " +
                                "3 - Work related,  " +
                                "4 - Personal situation,  " +
                                "5 - Rescheduled,  " +
                                "99 - Not known ")]
        [Example(Description = "1")]
        public ReasonForNonAttendance? ReasonForNonAttendance { get; set; }

        [Display(Description = "Date and time of the last modification to the record.  This time is auto-generated by CDS 2.0 if a value is not supplied")]
        [Example(Description = "2018-06-21T14:45:00")]
        public DateTime? LastModifiedDate { get; set; }

        [StringLength(10, MinimumLength = 10)]
        [Display(Description = "Identifier of the touchpoint who made the last change to the record")]
        [Example(Description = "0000000001")]
        public string LastModifiedTouchpointId { get; set; }

        public void SetDefaultValues()
        {
            if (!LastModifiedDate.HasValue)
                LastModifiedDate = DateTime.UtcNow;
        }

    }
}
