using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using NCS.DSS.Sessions.ReferenceData;
using NCS.DSS.Sessions.Annotations;

namespace NCS.DSS.Sessions.Models
{
    public class Session
    {
        [Required]
        [Example(Description = "b8592ff8-af97-49ad-9fb2-e5c3c717fd85")]
        [Display(Description = "Unique identifier of the appointment record")]
        public Guid SessionId { get; set; }

        [Example(Description = "b8592ff8-af97-49ad-9fb2-e5c3c717fd85")]
        [Display(Description = "Unique identifier to the related interaction resource")]
        public Guid InteractionId { get; set; }

        [Display(Description = "Date and time of the session with the customer")]
        [Example(Description = "2018-06-21T14:45:00")]
        public DateTime DateandTimeOfSession { get; set; }

        [Display(Description = "PostCode of the session or appointment venue where applicable")]
        [RegularExpression(@"([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A - Za - z][0 - 9][A - Za - z]) | 
                                            ([A - Za - z][A - Ha - hJ - Yj - y][0 - 9]?[A - Za - z]))))\\s?[0-9] [A-Za-z]{2})", 
                                            ErrorMessage = "Postcode must be in valid UK format as specified in the UK Government Data Standard.")]
        [StringLength(10)]
        public string VenuePostCode { get; set; }

        [Display(Description = "Indicator to say whether the session was attended or not")]
        [Example(Description = "true/false")]
        public bool SessionAttended { get; set; }

        [Display(Description = "See DSS Reference Data Resource for values  (Reason For Non Attendance) reference data")]
        [Example(Description ="1")]
        public ReasonForNonAttendance ReasonForNonAttendanceId { get; set; }

        [Display(Description = "Date and time of the last modification to the record.  This time is auto-generated by CDS 2.0 if a value is not supplied")]
        [Example(Description = "2018-06-21T14:45:00")]
        public DateTime LastModifiedDate { get; set; }

        [Display(Description = "Identifier of the touchpoint who made the last change to the record.  This value will be taken from the HTTP method header and is not needed to be supplied as a parameter")]
        [Example(Description = "b8592ff8-af97-49ad-9fb2-e5c3c717fd85")]
        public Guid LastModifiedTouchpointId { get; set; }
    }
}
